spring:
  datasource:
    username: root
    password: zhx
    url: jdbc:mysql://192.168.109.138:3306/mall_wms
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-ware

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml    # 如果写成“classpath:/mapper/**/*.xml”代表不止扫描自己的classpath，还扫描别人的
  global-config:
    db-config:
      id-type: auto     # 代表主键自增

# 端口号
server:
  port: 11000

logging:
  level:
    com.hxzhou: debug